#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

# Determine the platform
if [[ `uname` == 'Linux' ]]; then
  export GNU_USERLAND=1
else
  export LINUX=
fi
if [[ `uname` == 'Darwin' ]]; then
  export OSX=1
else
  export OSX=
fi

# Set default text editor
export VISUAL=vim
export EDITOR="$VISUAL"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add home bin
if [[ -d "$HOME/.bin/" ]]; then
  export PATH=$HOME/.bin:$PATH
fi
if [[ -d "$HOME/bin/" ]]; then
  export PATH=$HOME/bin:$PATH
fi

# Add locally bins
if [[ -d "/opt/local/bin/" ]]; then
  export PATH=/opt/local/bin:$PATH
fi

# Add locally bins
if [[ -d "/usr/sbin/" ]]; then
  export PATH=$PATH:/usr/sbin:/sbin
fi

# Add locally bins
if [[ -d "/usr/local/" ]]; then
  export PATH=$PATH:/usr/local
fi

# Go Lang Setup
if [[ -d "$HOME//" ]]; then
  export GOPATH=$HOME/gopath
  alias go-xbuild='CGO_ENABLED=0 gox -osarch="darwin/amd64 linux/amd64 linux/386" && CC="i686-w64-mingw32-gcc" CGO_ENABLED=1 gox -osarch="windows/386"'
fi

if [[ -d "$HOME/gopath/bin/" ]]; then
  export PATH=$HOME/gopath/bin:$PATH
  export GOPATH=/$HOME/gopath
fi

if [[ -d "$HOME/goroot" ]]; then
  export PATH=$PATH:$HOME/goroot/bin
  export GOROOT=/$HOME/goroot
fi

# Vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# Add gcloud
if [[ -d "$HOME/devtools/google-cloud-sdk" ]]; then
  export PATH=$HOME/devtools/google-cloud-sdk/bin:$PATH
  # The next line enables bash completion for gcloud.
  source "$HOME/devtools/google-cloud-sdk/completion.zsh.inc"
  # The next line enables shell command completion for gcloud.
  source "$HOME/devtools/google-cloud-sdk/path.zsh.inc"
fi

# JumpCloud Go Directory
if [[ -d "$GOPATH/src/github.com/TheJumpCloud" ]]; then
  alias -g gojump=$GOPATH/src/github.com/TheJumpCloud
fi
# Increase the maximum open files. This is useful for filewatcher programs (such as node-dev)
#ulimit -n 10000

## Aliases ##
alias myip="curl https://icanhazip.com"
alias mykey="cat $HOME/.ssh/id_rsa.pub"
alias reload-zsh-config='source ~/.zshrc'
alias gen-strong-sshkey='ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)-$(date -I)"'
alias vagrant-ansible-playbook='ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory --private-key=.vagrant/machines/default/virtualbox/private_key -u vagrant'
# Could be a git alias, but it had trouble finding pbcopy
alias git-hash='git rev-parse HEAD && git rev-parse HEAD | pbcopy'

# Manual Autocorrect Overrides
alias subl='nocorrect subl'

#Jumpcloud Specific Aliases
alias fetch-agent-staging='scp -r travis@staging.jumpcloud.com:/opt/provisioning-server/files/* ~/workspace/TheJumpCloud/SI/agent-files/'
alias rsync-agent-staging='rsync -avz --progress travis@staging.jumpcloud.com:/opt/provisioning-server/files/ ~/workspace/TheJumpCloud/SI/agent-files/'
alias rsync-agent-test='rsync -avz --progress travis@test.jumpcloud.com:/opt/provisioning-server/files/ ~/workspace/TheJumpCloud/SI/agent-files/'
#alias load-int-fixture='mongorestore -db SI ~/workspace/TheJumpCloud/SI/test/webui/integration/fixture/SI-integration'
#alias load-alarm-int-fixture='mongorestore -db SI ~/workspace/TheJumpCloud/SI/test/webui/integration/fixture/alarms/SI-integration'
##alias load-personal-fixture='mongorestore -db SI ~/workspace/TheJumpCloud/mongodumps/personal/SI'
#alias restart-ramdb='~/workspace/TheJumpCloud/SI/bin/mongod-ramdb-linux stop;~/workspace/TheJumpCloud/SI/bin/mongod-ramdb-linux start'
#alias reload-ramdb='restart-ramdb;load-int-fixture'
#alias reload-personal-ramdb='restart-ramdb;load-personal-fixture'
#alias reload-alarm-ramdb='restart-ramdb;load-alarm-int-fixture'
alias drop-test-dbs='mongo ~/workspace/TheJumpCloud/SI/bin/queries/drop-SI-Test-dbs.js'

function gcloud-ssh () {
  if [[ -n $1 ]]; then
    gcloud compute ssh --ssh-flag="-A" $1 $2 $3
  else
    echo "Please pass in the instance name"
  fi
}

# Load private environment files
if [ -f $HOME/.private-env ]; then
  source $HOME/.private-env
fi

# Always set the ssh agent in the same place
if [ "$SSH_AUTH_SOCK" != "$HOME/.ssh/ssh_auth_sock" ]; then
  ln -sf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock"
fi
